document.writeln("<!--头部 start-->");
document.writeln("");
document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD HTML 4.01 Transitional//EN\' \'http://www.w3.org/TR/html4/loose.dtd\'>");
document.writeln("<!--三级联动-->");
document.writeln("<link href=\'http://www.weiyun5.com/resources/mall/css/city-picker.css\' rel=\'stylesheet\'>");
document.writeln("<!--头部 start-->");
document.writeln("<script type=\'text/javascript\' src=\'http://qzonestyle.gtimg.cn/qzone/openapi/qc_loader.js\' data-appid=\'101358714\' charset=\'utf-8\'></script>");
document.writeln("<header>");
document.writeln("    <div class=\'top1\'>");
document.writeln("        <div class=\'center\' style=\'overflow: initial;\'>");
document.writeln("            <p class=\'welcom\'>欢迎光临危运网！</p>");
document.writeln("            <a href=\'http://www.wlkg.com/publishCarSource.html\'><img src=\'http://www.weiyun5.com/resources/mall/images/icon-che.png\' />发布车源信息</a>");
document.writeln("            <div class=\'line\'>|</div>");
document.writeln("            <a href=\'http://www.wlkg.com/foreground/member/index?type=11\'><img src=\'http://www.weiyun5.com/resources/mall/images/icon-huo.png\' />发布货源信息</a>");
document.writeln("            <div class=\'right\'> 欢迎，");
document.writeln("                <p class=\'welcom2\'>");
document.writeln("                    田哥");
document.writeln("                </p>");
document.writeln("");
document.writeln("                <div class=\'line\'>|</div>");
document.writeln("                <a href=\'http://www.wlkg.com/center/personCenter.html\'>个人中心</a>");
document.writeln("                <div class=\'line\'>|</div>");
document.writeln("                <a href=\'javascript:;\' onclick=\'logoutMember();\'>退出</a>");
document.writeln("");
document.writeln("                <div class=\'line\'>|</div>");
document.writeln("                <a href=\'http://www.wlkg.com/login.html\'>登录</a>");
document.writeln("                <div class=\'line\'>|</div>");
document.writeln("                <a href=\'http://www.wlkg.com/register.html\'>注册</a>");
document.writeln("");
document.writeln("                <div class=\'line\'>|</div>");
document.writeln("                <div onclick=\'top.window.location.href = \'http://www.weiyun5.com/about?type=map\';\' class=\'s-lang-box\'>网站地图");
document.writeln("                    <div class=\'s-language\' style=\' display:none;\'>");
document.writeln("                        <div class=\'p-map1\'>");
document.writeln("");
document.writeln("                            <h1><a href=\'http://www.weiyun5.com/article/index\'>行业资讯</a></h1>");
document.writeln("                            <ul>");
document.writeln("");
document.writeln("                                <li><a href=\'http://www.weiyun5.com/article/index\'>最新资讯</a></li>");
document.writeln("");
document.writeln("                                <li style=\'width:5%; color:#ddd;\'>|</li>");
document.writeln("");
document.writeln("                                <li><a href=\'http://www.weiyun5.com/article/index?program=6\'>政策法规</a></li>");
document.writeln("");
document.writeln("                                <li style=\'width:5%; color:#ddd;\'>|</li>");
document.writeln("");
document.writeln("                                <li><a href=\'http://www.weiyun5.com/article/index?program=7\'>行业新闻</a></li>");
document.writeln("");
document.writeln("                                <li><a href=\'http://www.weiyun5.com/article/index?program=8\'>化工详情</a></li>");
document.writeln("");
document.writeln("                                <li style=\'width:5%; color:#ddd;\'>|</li>");
document.writeln("");
document.writeln("                                <li><a href=\'http://www.weiyun5.com/article/index?program=9\'>热门视频</a></li>");
document.writeln("");
document.writeln("                                <li style=\'width:5%; color:#ddd;\'>|</li>");
document.writeln("");
document.writeln("                                <li><a href=\'http://www.weiyun5.com/exhibition/index\'>展会信息</a></li>");
document.writeln("");
document.writeln("                            </ul>");
document.writeln("");
document.writeln("                            <h1><a href=\'http://www.weiyun5.com/foreground/member/index?type=10\'>个人中心</a></h1>");
document.writeln("                            <ul>");
document.writeln("");
document.writeln("                                <li><a href=\'http://www.weiyun5.com/foreground/member/index?type=10\'>会员中心</a></li>");
document.writeln("");
document.writeln("                                <li style=\'width:5%; color:#ddd;\'>|</li>");
document.writeln("");
document.writeln("                                <li><a href=\'http://www.weiyun5.com/foreground/member/index?type=20\'>安全设置</a></li>");
document.writeln("");
document.writeln("                                <li style=\'width:5%; color:#ddd;\'>|</li>");
document.writeln("");
document.writeln("                                <li><a href=\'http://www.weiyun5.com/foreground/member/index?type=30\'>我的论坛</a></li>");
document.writeln("");
document.writeln("                            </ul>");
document.writeln("");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'center\'>");
document.writeln("        <div class=\'repoter-img\' style=\'margin:25px 0 0 0\'>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'top2\'>");
document.writeln("        <div class=\'center\' style=\' overflow: visible;\'> <a href=\'http://www.weiyun5.com/\'><img src=\'http://www.weiyun5.com/upload/attached/image/20190422/wyw_20190422151908.png\' class=\'logo\'/></a>");
document.writeln("            <div class=\'jq22-search-form right\'>");
document.writeln("                <div id=\'search-bd\' class=\'search-bd\'>");
document.writeln("                    <ul>");
document.writeln("                        <li class=\'selected\' value=\'1\'>货源</li>");
document.writeln("                        <li value=\'2\'>车源</li>");
document.writeln("                        <li value=\'3\'>资讯</li>");
document.writeln("                        <li value=\'4\'>论坛</li>");
document.writeln("                        <li value=\'5\'>企业</li>");
document.writeln("                        <li value=\'6\'>百科</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div id=\'search-hd\' class=\'search-hd\'>");
document.writeln("                    <form id=\'headQuick\'>");
document.writeln("                        <input type=\'hidden\' id=\'quickUrl\' name=\'quickUrl\' value=\'1\'>");
document.writeln("                        <div class=\'search-bg\'></div>");
document.writeln("                        <input type=\'text\' id=\'s1\' class=\'search-input\'>");
document.writeln("                        <input type=\'text\' id=\'s2\' class=\'search-input\' style=\'display: none;\'>");
document.writeln("                        <input type=\'text\' id=\'s3\' name=\'articleTitle\' class=\'search-input\' style=\'width: 450px; display: none;\'>");
document.writeln("                        <input type=\'text\' id=\'s4\' name=\'bbsTopic\' class=\'search-input\' style=\'width: 450px; display: none;\'>");
document.writeln("                        <input type=\'text\' id=\'s5\' name=\'enterpriseName\' class=\'search-input\' style=\'width: 450px; display: none;\'>");
document.writeln("                        <input type=\'text\' id=\'s6\' name=\'encyclopediaTitle\' class=\'search-input\' style=\'width: 450px; display: none;\'>");
document.writeln("                        <span class=\'s1 pholder\'>");
document.writeln("        	 <input name=\'goodDepart\' type=\'text\' id=\'city-picker3\' class=\'form-control\' readonly type=\'text\' data-toggle=\'city-picker\' placeholder=\'请输入出发城市\' />");
document.writeln("             <span style=\'float:left;\'>&nbsp;&nbsp;&nbsp;--&nbsp;&nbsp;&nbsp;</span>");
document.writeln("             <input name=\'goodArrvie\' type=\'text\' id=\'city-picker3\' class=\'form-control\' readonly type=\'text\' data-toggle=\'city-picker\' placeholder=\'请输入出发城市\' />");
document.writeln("        </span>");
document.writeln("                        <span class=\'s2 pholder\'>");
document.writeln("        	 <input name=\'carDepart\' type=\'text\' id=\'city-picker3\' class=\'form-control\' readonly type=\'text\' data-toggle=\'city-picker\' placeholder=\'请输入出发城市\' />");
document.writeln("             <span style=\'float:left;\'>&nbsp;&nbsp;&nbsp;--&nbsp;&nbsp;&nbsp;</span>");
document.writeln("             <input name=\'carArrvie\' type=\'text\' id=\'city-picker3\' class=\'form-control\' readonly type=\'text\' data-toggle=\'city-picker\' placeholder=\'请输入出发城市\' />");
document.writeln("        </span> <span class=\'s3 pholder\' style=\'display: none;\'>请输入关键字</span>");
document.writeln("                        <span class=\'s4 pholder\' style=\'display: none;\'>请输入关键字</span>");
document.writeln("                        <span class=\'s5 pholder\' style=\'display: none;\'>请输入关键字</span>");
document.writeln("                        <span class=\'s6 pholder\' style=\'display: none;\'>请输入关键字</span>");
document.writeln("                    </form>");
document.writeln("                    <button id=\'submit\' onclick=\'quickUrl();\' class=\'btn-search\' value=\'搜索\'>搜索</button>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</header>");
document.writeln("<!--头部 end-->");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<!--导航栏-->");
document.writeln("<div class=\'nav\'>");
document.writeln("    <div class=\'center3\' style=\'position:relative\'>");
document.writeln("        <ul class=\'nav-main\'>");
document.writeln("            <li><a href=\'http://www.wlkg.com/\' class=\'hover\'>首页</a>");
document.writeln("                <div class=\'line-nav\'>|</div>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'http://www.wlkg.com/carSource.html\' >车源信息</a>");
document.writeln("                <div class=\'line-nav\'>|</div>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'http://www.wlkg.com/goodSource.html\' >货源信息</a>");
document.writeln("                <div class=\'line-nav\'>|</div>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'http://www.wlkg.com/industryInfo.html\' >行业资讯</a>");
document.writeln("                <div class=\'line-nav\'>|</div>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'http://www.wlkg.com/carServer.html\' >车辆服务</a>");
document.writeln("                <div class=\'line-nav\'>|</div>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'http://www.wlkg.com/businessShow.html\' >企业展示</a>");
document.writeln("                <div class=\'line-nav\'>|</div>");
document.writeln("            </li>");
document.writeln("            <li id=\'li-1\'>");
document.writeln("                <a href=\'#\' >人才招聘</a><div class=\'line-nav\'>|</div>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'http://www.weiyun5.com/encyclopedia/index\' >危险品百科</a>");
document.writeln("                <div class=\'line-nav\'>|</div>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'http://www.weiyun5.com/BBS/index\' >危运论坛</a>");
document.writeln("                <div class=\'line-nav\'>|</div>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'http://www.weiyun5.com/exhibition/index\' >展会信息</a>");
document.writeln("                <div class=\'line-nav\'></div></li>");
document.writeln("");
document.writeln("        </ul>");
document.writeln("        <!--隐藏盒子-->");
document.writeln("        <div id=\'box-1\' class=\'hidden-box hidden-loc-index\'>");
document.writeln("            <ul>");
document.writeln("                <li><a href=\'http://www.wlkg.com/employer.html\' style=\'padding:0 10px;\'>招聘信息</a></li>");
document.writeln("                <li><a href=\'http://www.wlkg.com/employee.html\' style=\'padding:0 10px;\'>求职信息</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<!--导航栏 end-->");
document.writeln("<!--搜索框-->");
document.writeln("<script>");
document.writeln("    $(function(){");
document.writeln("        //通用头部搜索切换");
document.writeln("        $(\'#search-hd .search-input\').on(\'input propertychange\',function(){");
document.writeln("            var val = $(this).val();");
document.writeln("            if(val.length > 0){");
document.writeln("                $(\'#search-hd .pholder\').hide(0);");
document.writeln("            }else{");
document.writeln("                var index = $(\'#search-bd li.selected\').index();");
document.writeln("                $(\'#search-hd .pholder\').eq(index).show().siblings(\'.pholder\').hide(0);");
document.writeln("            }");
document.writeln("        })");
document.writeln("        $(\'#search-bd li\').click(function(){");
document.writeln("            var index = $(this).index();");
document.writeln("            $(\'#search-hd .pholder\').eq(index).show().siblings(\'.pholder\').hide(0);");
document.writeln("            $(\'#search-hd .search-input\').eq(index).show().siblings(\'.search-input\').hide(0);");
document.writeln("            $(this).addClass(\'selected\').siblings().removeClass(\'selected\');");
document.writeln("            $(\'#search-hd .search-input\').val(\'\');");
document.writeln("            document.getElementById(\'quickUrl\').value=$(this).val();");
document.writeln("        });");
document.writeln("    })");
document.writeln("</script>");
document.writeln("<script>");
document.writeln("    $(\'.nav ul li a\').click(function(){");
document.writeln("        $(\'.nav ul li a\').removeClass(\'hover\');");
document.writeln("        $(this).addClass(\'hover\');");
document.writeln("    });");
document.writeln("</script>");
document.writeln("<!--网站地图-->");
document.writeln("<script>");
document.writeln("    $(\'.s-lang-box\').hover(function(){");
document.writeln("        $(\'.s-language\').toggle();");
document.writeln("    });");
document.writeln("</script>");
document.writeln("<!--网站地图 end-->");
document.writeln("<!--导航下拉菜单-->");
document.writeln("<script>");
document.writeln("    $(document).ready(function(){");
document.writeln("//    nav-li hover e");
document.writeln("        var num;");
document.writeln("        $(\'.nav-main>li[id]\').hover(function(){");
document.writeln("            /*图标向上旋转*/");
document.writeln("            $(this).children(\'a\').removeClass().addClass(\'hover-up\');");
document.writeln("            /*下拉框出现*/");
document.writeln("            var Obj = $(this).attr(\'id\');");
document.writeln("            num = Obj.substring(3, Obj.length);");
document.writeln("            $(\'#box-\'+num).slideDown(300);");
document.writeln("        },function(){");
document.writeln("            /*图标向下旋转*/");
document.writeln("            $(this).children(\'a\').removeClass().addClass(\'hover-down\');");
document.writeln("            /*下拉框消失*/");
document.writeln("            $(\'#box-\'+num).hide();");
document.writeln("        });");
document.writeln("//    hidden-box hover e");
document.writeln("        $(\'.hidden-box\').hover(function(){");
document.writeln("            /*保持图标向上*/");
document.writeln("            $(\'#li-\'+num).children(\'a\').removeClass().addClass(\'hover-up\');");
document.writeln("            $(this).show();");
document.writeln("        },function(){");
document.writeln("            $(this).slideUp(200);");
document.writeln("            $(\'#li-\'+num).children(\'a\').removeClass().addClass(\'hover-down\');");
document.writeln("        });");
document.writeln("    });");
document.writeln("    function quickUrl(){");
document.writeln("        var type=document.getElementById(\'quickUrl\').value;");
document.writeln("        var url=\'\';");
document.writeln("        var params=$(\'#headQuick\').serialize();");
document.writeln("        if(type==1){");
document.writeln("            url=\'goodSource.html\';");
document.writeln("        }");
document.writeln("        if(type==2){");
document.writeln("            url=\'carSource.html\';");
document.writeln("        }");
document.writeln("        if(type==3){");
document.writeln("            url=\'article/index?\';");
document.writeln("        }");
document.writeln("        if(type==4){");
document.writeln("            url=\'BBS/index?\';");
document.writeln("        }");
document.writeln("        if(type==5){");
document.writeln("            url=\'enterprise/index?\';");
document.writeln("        }");
document.writeln("        if(type==6){");
document.writeln("            url=\'encyclopedia/index?\';");
document.writeln("        }");
document.writeln("        // top.window.location.href = \'http://www.weiyun5.com/\'+url+params;");
document.writeln("        top.window.location.href = \'http://www.wlkg.com/\'+url");
document.writeln("    }");
document.writeln("    function logoutMember(){");
document.writeln("        QC.Login.signOut();");
document.writeln("        top.window.location.href = \'http://api.wlkg.com/api/user/logout\';");
document.writeln("    }");
document.writeln("</script>");
document.writeln("<!--导航下拉菜单 end-->");
document.writeln("<script src=\'http://www.weiyun5.com/upload/city-data.js\'></script>");
document.writeln("<script src=\'http://www.weiyun5.com/resources/mall/js/city-picker.js\'></script>");
document.writeln("");
document.writeln("<!--头部 end-->");